server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'api-gateway'
          __path__: '/var/log/spring/api-gateway.*.log'

  - job_name: 'data-service'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'data-service'
          __path__: '/var/log/spring/data-service.*.log'

  - job_name: 'websocket-service'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'websocket-service'
          __path__: '/var/log/spring/websocket-service.*.log'

  - job_name: 'scrapper-service'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'scrapper-service'
          __path__: '/var/log/spring/scrapper-service.*.log'

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'frontend-service'
          __path__: '/var/log/spring/frontend-service.*.log'