global:
  scrape_interval: 20s
  scrape_timeout: 15s
  evaluation_interval: 20s

scrape_configs:

  - job_name: 'spark-middleware-scrapper-data-api'
    metrics_path: '/actuator/prometheus'
    scheme: http

    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
        refresh_interval: 30s

    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_ip_addr, __meta_eureka_app_instance_port]
        regex: '(.*);(\d+)'
        replacement: '${1}:${2}'
        target_label: __address__

      - source_labels: [__meta_eureka_app_instance_id]
        target_label: instance

      - source_labels: [__meta_eureka_app_instance_secure_vip_address]
        replacement: '${1}'
        target_label: job

      - source_labels: [__meta_eureka_app_instance_secure_vip_address]
        replacement: '${1}'
        target_label: application