server:
  port: 9001

spring:
  application:
    name: data-service
  jackson:
    time-zone: Europe/Warsaw
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db/sqlite.db
    username:
    password:
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: data-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true