spring:
  application:
    name: eureka-server
  banner:
    location: classpath:banner.txt

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 0.0 # 0.0 SET FOR DISABLING ZIPKIN IN LOCALHOST DEV ENVIRONMENT
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: eureka-server
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true