server:
  port: 4200

spring:
  application:
    name: frontend-service
  jackson:
    time-zone: Europe/Warsaw

websocket:
  url: http://localhost:9999/websocket

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  observations:
    key-values:
      application: frontend-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true