server:
  port: 9002

spring:
  application:
    name: websocket-service
  jackson:
    time-zone: Europe/Warsaw

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

management:
  tracing:
    sampling:
      probability: 0.0 # 0.0 SET FOR DISABLING ZIPKIN IN LOCALHOST DEV ENVIRONMENT
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: websocket-service
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true